# Generated by Django 4.0.4 on 2022-05-26 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('mobile_no', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('travelling_type', models.CharField(choices=[('Two Wheeler', 'Two Wheeler'), ('Four Wheeler', 'Four Wheeler'), ('Public Transport', 'Public Transport')], max_length=50)),
                ('dob', models.DateField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateField()),
                ('checkout_time', models.TimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.employee_registration')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkin_time', models.TimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.employee_registration')),
            ],
        ),
    ]
