# Generated by Django 4.0.4 on 2022-05-26 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_registration',
            name='travelling_type',
        ),
        migrations.RemoveField(
            model_name='employee_registration',
            name='username',
        ),
        migrations.AddField(
            model_name='employee_registration',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='logdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(auto_now_add=True)),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('mod_Trans', models.CharField(choices=[('Public Transport', 'Public Transport'), ('Bike', 'Bike'), ('Car', 'Car')], max_length=50)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.employee_registration')),
            ],
        ),
    ]
