# Generated by Django 4.0.4 on 2022-05-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_remove_employee_registration_travelling_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logdetails',
            old_name='User',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='logdetails',
            old_name='mod_Trans',
            new_name='mod_trans',
        ),
        migrations.AlterField(
            model_name='employee_registration',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logdetails',
            name='check_in',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logdetails',
            name='check_out',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
