# Generated by Django 4.0.4 on 2022-05-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_rename_user_logdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdetails',
            name='check_out',
            field=models.TimeField(null=True),
        ),
    ]
